const express = require("express");
const router = express.Router();
const KitchenOrdersController = require("../controllers/KitchenOrdersController");
const authMiddleware = require("../middleware/authMiddleware");
router.get("/", authMiddleware, KitchenOrdersController.getOrders);
router.put("/status", authMiddleware, KitchenOrdersController.updateBarOrderStatus);
router.post("/items", authMiddleware, KitchenOrdersController.getOrderItems);
router.post("/scan", authMiddleware, KitchenOrdersController.processBarcodeScan);
router.get("/scanned-items/:orderNumber", authMiddleware, KitchenOrdersController.getScannedItemsFromSession);
router.delete("/scanned-items/:orderNumber", authMiddleware, KitchenOrdersController.clearScannedItemsFromSession);
router.put("/cancel", authMiddleware, KitchenOrdersController.cancelBarOrderItem);
router.get("/active", authMiddleware, KitchenOrdersController.getActiveBarOrders);
router.put("/notifications/read", authMiddleware, KitchenOrdersController.markNotificationAsRead);
router.get("/cocktail/:itemId", authMiddleware, KitchenOrdersController.getCocktailDetailsById);
router.get("/cancelled-orders", authMiddleware, KitchenOrdersController.getCancelledOrders);
router.get("/order-history", authMiddleware, KitchenOrdersController.getOrderHistory);
router.get("/cancelled-order-details/:orderNumber", authMiddleware, KitchenOrdersController.getOrderDetailsByOrderNumber);
router.get("/order-history-details/:orderNumber", authMiddleware, KitchenOrdersController.getOrderHistoryItemDetails);
module.exports = router;