CREATE TABLE IF NOT EXISTS xxafmc_stock_reservation_totals (
  item_code INT NOT NULL,
  reserved_qty INT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (item_code)
);
